knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        options:    []

#knp_snappy:
#    pdf:
#        enabled:    true
#        binary:     "\"F:\\wkhtmltox\\bin\\wkhtmltopdf.exe\""
#        options:    []
#    image:
#        enabled:    true
#        binary:     "\"F:\\wkhtmltox\\bin\\wkhtmltoimage.exe\""
#        options:    []
